### ISSUE TITLE
Supporting non-Ubuntu Linux OS

### ISSUE THREAD

**Issue by blegat** [rdeits/DrakeVisualizer.jl#42]
What is the long term plan for supporting Linux OS like ArchLinux or Fedora ? Having prebuilt binaries for them or using a fallback that downloads director and build it from source ?

**Comment by rdeits** [comment]
Good point. For now, the workaround is just to build Director from source manually. But yes, I think having DrakeVisualizer.jl fall back to building the sources is the right thing to do. The thing that makes this slightly more difficult is that building Director requires a relatively modern version of cmake (newer than what Ubuntu 14.04 has available). Since cmake isn't a library, I can't hook it directly in as a BinDeps.jl dependency: https://github.com/JuliaLang/BinDeps.jl/issues/213 

I think what I'd like to do is make a CMakeWrapper.jl package that downloads a modern cmake version and provides a BinDeps interface. That would let us build DrakeVisualizer, and would also fix the build issues with packages like LCMCore.jl.

**Comment by rdeits** [comment]
On that note: https://github.com/rdeits/CMakeWrapper.jl

I'm testing it out here: https://github.com/rdeits/LCMCore.jl/pull/6

Once that works, I'll try using it to build DrakeVisualizer.jl.

**Comment by rdeits** [comment]
The one part I'm not sure about is how to install the VTK python bindings without Apt. Could you check your package manager for its `python-vtk` equivalent and let me know what I need to include?

**Comment by blegat** [comment]
It seems to be in the [AUR](https://aur.archlinux.org/packages/python-vtk/).
So you need to do
```sh
$ git clone https://aur.archlinux.org/vtk-multi-python.git
$ cd vtk-multi-python
$ makepkg -si
```

**Comment by rdeits** [comment]
Ok, that's great. Since I have no machines running Arch, this isn't something I can test myself. Is it reasonable to just have Arch users install `vtk-multi-python` themselves?

**Comment by blegat** [comment]
Yes definitely, in fact I was going to suggest you the same thing.
I am currently trying this AUR package, it is taking ages (it downloaded `VTKData` and `VTKLargeData` which took a long time) ^^

**Comment by rdeits** [comment]
Yeah, VTK always takes a long time, unfortunately.

**Comment by blegat** [comment]
Thank you !

**Comment by pvazteixeira** [comment]
I just added a comment to eabf4f8262a77c5f69ee512cc25e1cfd0e4c297c - while building from source is fine, at least under Debian Jessie (8.7) you can just apt-get install the dependencies.

**Comment by rdeits** [comment]
Ok, excellent! I'll run on the vtk `apt-get` provider for Debian, and I'll turn on the Ubuntu 14.04 binaries for Debian Jessie.

**Comment by pvazteixeira** [comment]
Great, thanks!
